name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust nightly
        run: |
          rustup toolchain install nightly
          rustup default nightly
          rustup component add rust-src --toolchain nightly
          rustup component add llvm-tools-preview --toolchain nightly

      - name: Install bootimage
        run: cargo install bootimage

      - name: Build
        run: cargo build --verbose
